"""empty message

Revision ID: 9abd4bebba99
Revises: 59292b174361
Create Date: 2025-07-22 16:57:36.421501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9abd4bebba99'
down_revision: Union[str, Sequence[str], None] = '59292b174361'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('collection_title_key'), 'collection', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('collection_title_key'), 'collection', ['title'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
