"""Initial database schema

Revision ID: bdf613a9994e
Revises: 9abd4bebba99
Create Date: 2025-08-08 14:26:43.942005

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bdf613a9994e'
down_revision: Union[str, Sequence[str], None] = '9abd4bebba99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('story', 'ethnography',
               existing_type=postgresql.ENUM('GERMAN', 'SLAVIC', 'CAUCASIAN', 'TURKIC', 'FRENCH', 'SCANDINAVIAN', 'ENGLISH_AND_IRISH', 'ITALIAN', 'SPANISH_AND_PORTUGUESE', 'GREEK', 'PERSIAN', 'INDIAN', 'CHINESE', 'JAPANESE', 'JEWISH', name='ethnography_enum'),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('story', 'ethnography',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.ENUM('GERMAN', 'SLAVIC', 'CAUCASIAN', 'TURKIC', 'FRENCH', 'SCANDINAVIAN', 'ENGLISH_AND_IRISH', 'ITALIAN', 'SPANISH_AND_PORTUGUESE', 'GREEK', 'PERSIAN', 'INDIAN', 'CHINESE', 'JAPANESE', 'JEWISH', name='ethnography_enum'),
               nullable=True)
    # ### end Alembic commands ###
