name: Deploy FairyTails

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests (if any)
      run: |
        echo "No tests configured yet"
        
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_IP }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          cd ${{ vars.PATH }}
          
          git config --global url."https://${{ secrets.GH_TOKEN }}@github.com/".insteadOf "https://github.com/"
          git pull origin main
          
          echo "${{ vars.ENV }}" > .env
          
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          
          alembic upgrade head
          
          sudo cp deploy/fairytails.service /etc/systemd/system/fairytails.service
          
          sudo systemctl daemon-reload
          sudo systemctl enable fairytails
          sudo systemctl restart fairytails
          
          sudo systemctl status fairytails --no-pager
          
          sleep 5
          if sudo systemctl is-active --quiet fairytails; then
            echo "✅ FairyTails service is running successfully"
          else
            echo "❌ FairyTails service failed to start"
            sudo journalctl -u fairytails --no-pager -n 20
            exit 1
          fi